name: Testing
on:
  push:

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
        env:
          CI: true

      # - name: Restore Dependency Cache
      #   id: cache-modules
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-{{ hashFiles('package-lock.json') }}

      # - name: Install dependencies
      #   if: steps.cache-modules.outputs.cache-hit != 'true'
      #   run: 

      # - name: Save Dependency Cache
      #   id: cache-modules
      #   uses: actions/cache@v2
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-{{ hashFiles('package-lock.json') }}
